import './global.css';
export const metadata = {
  title: 'Crea con Gemini',
  description: 'Generated by NoreDev',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
